### ISSUE TITLE
0.2.6 release gone after account name change

### ISSUE THREAD

**Issue by sysfu** [coneill-math/Pandorita#21]
I have Pandorita 0.2.6 installed on MacOS. 

Went to check for an update today using the in-app check update feature but it failed.

Tried visiting https://github.com/musicman3320/Pandorita but link redirected to https://github.com/coneill-math/Pandorita.

The thing that confuses me is that this project page does not contain the 0.2.6 release.

What's the status?

**Comment by coneill-math** [comment]
I am glad to hear you are using Pandorita!  Unfortunately, I have not had much time to work on this project in quite some time.  

The good news is, the update error you reported should be an easy fix on my end: I recently changed my username from musicman3320 to coneill-math, and the Sparkle update framework is still using the old URL.  I will try to do this in the next few days and push an update (you will probably have to manually update once this happens, since Sparkle will still be broken on your end).  

I wouldn't be too spooked by the 0.2.6 ambiguity.  My local copy has this version number as well; I probably pushed the 0.2.6 update and forgot to change a few of the Github pages.  

Thank you for your patience, and for continuing to use Pandorita.  Perhaps someday in the future I will be able to return to this project in full force.

**Comment by coneill-math** [comment]
Just posted an update.  This should fix the URL change issue, and future updates should work as expected.
